name: Codecov

on:
  push:
    branches: [main]
    paths: [".github/codecov.json"]

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - uses: codecov/codecov-action@v7
        with:
          files: .github/codecov.json
          disable_search: true
          token: ${{ secrets.CODECOV_TOKEN }}
